on: [pull_request]
name: Test
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Requirements
        run: |
          GO111MODULES=off; go mod vendor
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      - name: Setup SSH Key Build and run e2e
        run : |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
          make e2e-build
          make e2e-run
          make install-shellcheck
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Test e2e
        run: |
          make check
          make e2e-test
      - name: Clean e2e
        run: make e2e-clean
